
version: "3.8"
services:
  db:
    image: postgres:13
    restart: always
    container_name: suprss_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-suprss}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-suprss}
      - POSTGRES_DB=${POSTGRES_DB:-suprss}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: suprss_server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - OAUTH_MICROSOFT_CLIENT_ID=${OAUTH_MICROSOFT_CLIENT_ID}
      - OAUTH_MICROSOFT_CLIENT_SECRET=${OAUTH_MICROSOFT_CLIENT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - SERVER_URL=${SERVER_URL}
    depends_on:
      - db
    ports:
      - "4000:4000"
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run start
      "

  client:
    build: ./frontend
    container_name: suprss_client
    depends_on:
      - server
    ports:
      - "3000:80"
volumes:
  db-data:
